## Configuration
font_family JetBrainsMono Nerd Font
font_size 12
bold_font auto
italic_font auto
bold_italic_font auto
remember_window_size no
initial_window_width 950
initial_window_height 500
cursor_blink_interval 0.5
cursor_stop_blinking_after 10
scrollback_lines 2000
wheel_scroll_min_lines 1
enable_audio_bell no
window_padding_width 12
hide_window_decorations yes
background_blur 32
background_opacity 0.6
dynamic_background_opacity yes
confirm_os_window_close 0

## tab colors
active_tab_foreground #000
active_tab_background #4681ca
active_tab_font_style bold-italic
inactive_tab_foreground #fcf9f9
inactive_tab_background #000000
inactive_tab_font_style normal
#tab_bar_background #000000

## Tab configuration
#tab_bar_style separator
#tab_fade 1
#tab_powerline_style separator
#tab_separator " ┇ "

tab_bar_style separator
tab_separator " ░ "
tab_title_template " {index}: {title} "
active_tab_title_template " {index}: {title} "
tab_bar_align left

## Shell integration
shell_integration enabled

## Scrollback
scrollback_lines 3000

## Terminal features
copy_on_select yes
strip_trailing_spaces smart

## cursor
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_color #1f19d3

allow_remote_control yes

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
