#!/bin/bash

#ip einlesen

get_ip() {

    # prüfen ob was übergeben wurde
    if [ $# -eq 1 ]; then
    # parameter übergeben
        karte=$1
    #wenn eine schnittstelle angegeben wurde
        ip=$(ip addr show $karte | grep 'inet ' | cut -d' ' -f 6 | head -1)

    else
        #wenn kein Parameter angegeben wurde
        karte=$(ls /sys/class/net/ | grep -v lo)
    # eingabe der gewünschten Karte
        echo " "
        echo "bitte Netzwerkkarte auswählen:"
        echo " "

    # ausgabe der vorhanden karten
        for auswahl in $karte; do

            echo "  => $auswahl"

        done
        echo " "

    # eingabe der gewünschten karte
        read -p "Netzwerkschnittstelle : " karte



    # existiert diese Karte?
        if [ ! -d "/sys/class/net/$karte" ]; then
    #wenn nicht
            echo "-------------------------------------------------"
            echo "Die Netzwerkschnittstelle $karte existiert nicht." >&2
            echo "-------------------------------------------------"


        else

    #wenn was eingegeben wurde
            if [ -n "$karte" ]; then
                # holen der ip
                ip=$(ip addr show $karte | grep 'inet ' | cut -d' ' -f 6 | head -1)

            else

    #wenn nix eingegeben wurde
                echo "------------------------"
                echo keine karte ausgesucht!!!
                echo "------------------------"
                exit 1
            fi

        fi

    fi

}

get_ip $1

    # ausgabe der ip adresse

if [ ! -d "/sys/class/net/$karte" ]; then

        echo " "

        else
        echo "-------------------------------------------- "
        echo "Die IP-Adresse von $karte ist: $ip"
        echo "-------------------------------------------- "

fi
