#!/bin/bash

# ort und dateitypen die angepasst werden sollen
pfad="/home/gc/bin/data/"
filter="*.pdf"

# Menue und überprüfung der auswahl
auswahl() {
    read -p "Auswahl der Funktion:
  1) Dateien Umbenennen
  2) prefix anhängen
  3) postfix anhängen
  4) Dateien Auflisten
  5) Exit
  Auswahl: " choice

    # Validate user input
    while [[ ! $choice =~ ^[1-5]$ ]]; do
        echo "Falsche Eingabe! Bitte wählen sie eine Zahl zwischen 1 und 5!"
        read -p "Auswahl der Funktion: " choice
    done
    #echo "die wahl war $choice"

}

#funktion umbenennen
umbenennen() {

    # Dateien einlesen

    datei=($(find "$pfad" -type f -name "$filter"))
    # ausgabe gefundene Dateien
    echo " "
    echo "gefundende Dateien: "
    #  echo "die datei $datei"

    for dateien in ${datei[@]}; do

        echo $dateien

    done
    # neuen Dateinamen erfahren

    echo " "
    read -p "einen neuen Dateinamen eingeben:" new_name
    echo " "
    echo "Dateien werden wie angegeben umbenannt: "
    #zahl nach dem Namen da alle gleich heissen

    anhang=1

    #ausgabe der gefundenen Dateien

    for dateien in ${datei[@]}; do

        neuer_name="$new_name$anhang.${dateien##*.}"
        echo "$dateien --> $pfad$neuer_name"

        ((anhang++))

    done
    echo " "
    read -p "möchten sie die Dateien umbenennen? (j/n): " ja
    echo " "
    if [[ $ja =~ ^[Jj]$ ]]; then

        # umbenennen
        anhang=1
        #umbenennen nach der bestätigunge
        for dateien in "${datei[@]}"; do
            neuer_name="$new_name$anhang.${dateien##*.}"
            mv "$dateien" "$pfad$neuer_name"
            ((anhang++))
        done
        echo "!!!!!!!!!!!!!!!!!!!!!!!"
        echo "umbenennen erfolgreich"
        echo "!!!!!!!!!!!!!!!!!!!!!!!"
    else
        echo "!!!!!!!!!!!!!!!!!!!!!!"
        echo "umbenennen abgebrochen"
        echo "!!!!!!!!!!!!!!!!!!!!!!"
    fi

}

prefix() {

    datei=($(find "$pfad" -type f -name "$filter"))
    # ausgabe gefundene Dateien
    echo " "
    echo "gefundende Dateien: "

    for dateien in ${datei[@]}; do

        echo $dateien

    done
    # neuen Dateinamen erfahren

    echo " "
    read -p "einen neuen prefix eingeben: " pref
    echo " "
    echo "Dateien werden wie angegeben umbenannt"

    #ausgabe der gefundenen Dateien

    for dateien in ${datei[@]}; do

        nname="${dateien##*/}"
        neuer_name="$pref-$nname"

        echo "$dateien --> $pfad$neuer_name"

    done

    echo " "
    read -p "möchten sie den präfix einfügen? (j/n): " ja
    echo " "

    if [[ $ja =~ ^[Jj]$ ]]; then

        # umbenennen

        #umbenennen nach der bestätigunge
        for dateien in "${datei[@]}"; do

            nname="${dateien##*/}"
            neuer_name="$pref-$nname"

            mv "$dateien" "$pfad$neuer_name"

        done

        echo "!!!!!!!!!!!!!!!!!!!"
        echo "prefix hinzugefügt"
        echo "!!!!!!!!!!!!!!!!!!!"
    else
        echo "!!!!!!!!!!!!!!!!!!"
        echo "aktion abgebrochen"
        echo "!!!!!!!!!!!!!!!!!!"
    fi

}

postfix() {

    echo

    datei=($(find "$pfad" -type f -name "$filter"))
    # ausgabe gefundene Dateien
    echo " "
    echo "gefundende Dateien: "

    for dateien in ${datei[@]}; do

        echo $dateien

    done
    # neuen Dateinamen erfahren

    echo " "
    read -p "einen neuen postix eingeben: " postf
    echo " "




    echo "Dateien werden wie angegeben umbenannt"

    #ausgabe der gefundenen Dateien

    for dateien in ${datei[@]}; do

        ausg="${dateien##*/}"
        nname="${ausg%.*}"
        # zusammensetzen Dateiname
        neuer_name="$pfad$nname-$postf.${dateien##*.}"
        echo "$dateien --> $pfad$neuer_name"

    done

    echo " "
    read -p "möchten sie einen Postfix einfügen? (j/n): " ja
    echo " "

    if [[ $ja =~ ^[Jj]$ ]]; then

        # umbenennen

        #umbenennen nach der bestätigunge
        for dateien in "${datei[@]}"; do

            ausg="${dateien##*/}"
            nname="${ausg%.*}"
            #zusammensetzen Dateiname
            neuer_name="$nname-$postf.${dateien##*.}"

            mv "$dateien" "$pfad$neuer_name"

        done

        echo "!!!!!!!!!!!!!!!!!!!"
        echo "postfix hinzugefügt"
        echo "!!!!!!!!!!!!!!!!!!!"
    else
        echo "!!!!!!!!!!!!!!!!!!"
        echo "aktion abgebrochen"
        echo "!!!!!!!!!!!!!!!!!!"
    fi

}

auflisten(){


 datei=($(find "$pfad" -type f -name "$filter"))
    # ausgabe gefundene Dateien
    echo " "
    echo "gefundende Dateien: "
    #  echo "die datei $datei"

 sortiert=($(sort -V <<< "${datei[@]}"))

    for dateien in ${sortiert[@]}; do


        echo "$dateien"
    done
echo
}




# hauptprogramm
while true; do
    auswahl

    case $choice in
    1) umbenennen ;;
    2) prefix ;;
    3) postfix ;;
    4) auflisten ;;
    5) exit ;;
    esac

done
